### ISSUE TITLE
Some projects I am Working On

### ISSUE THREAD

**Issue by skaiheda** [robhinds/robhinds.github.io#10] opened 2019-01-01 23:14 UTC
it doesnt show projects

**Comment by robhinds** [comment] 2019-01-02 09:24
Do you have an example (e.g. is it deployed on your github page)? 

The project names need to be configured URLs in the config yaml file, are those correct?

Currently displaying and working ok on my setup: https://robhinds.github.io/

**Comment by skaiheda** [comment] 2019-01-02 18:02
sorry. this problem was not related with your repo. I don't know why. But today in the morning , this section was already available.

**Comment by skaiheda** [comment] 2019-01-02 19:21
It happens again ;/ 
![rob hinds 1-2-2019 11-19-46 pm](https://user-images.githubusercontent.com/23127740/50608130-0d99e580-0ee5-11e9-844d-2fe9d653efee.png)

**Comment by robhinds** [comment] 2019-01-02 22:27
Ok I will take a look tomorrow, everyone I check out looks ok. Possibly related to some GitHub outages today (I was experiencing 502s just hitting GitHub.com and lots on Twitter reporting issues)

**Comment by robhinds** [comment] 2019-01-02 22:33
Yep looks like there were API outages confirmed, but GitHub pages still worked, which would explain why it was just the projects loading that failed (whilst the test of the page was ok)

**Comment by robhinds** [comment] 2019-01-14 20:44
I will close this issue, if you are no longer experiencing the problem now GitHub outage has stopped?

**Comment by skaiheda** [comment] 2019-01-15 00:01
okay.there is no problem.thanks for repo)

**Closed as completed** 2019-01-15 20:59 UTC
